### ISSUE TITLE
bug in vscode extension

### ISSUE THREAD

**Issue by caleb15** [lyft/react-javascript-to-typescript-transform#53]
extension version 1.10.0

Happens when I activate the extension.

```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2379 Error: Cannot read property 'kind' of undefined
	at Object.isSourceFile (c:\Users\work\.vscode\extensions\mohsen1.react-javascript-to-typescript-transform-vscode-1.10.0\node_modules\typescript\lib\typescript.js:11833:21)
	at Object.printNode (c:\Users\work\.vscode\extensions\mohsen1.react-javascript-to-typescript-transform-vscode-1.10.0\node_modules\typescript\lib\typescript.js:68607:40)
	at Object.compile (c:\Users\work\.vscode\extensions\mohsen1.react-javascript-to-typescript-transform-vscode-1.10.0\node_modules\react-js-to-ts\dist\compiler.js:39:27)
	at Object.run (c:\Users\work\.vscode\extensions\mohsen1.react-javascript-to-typescript-transform-vscode-1.10.0\node_modules\react-js-to-ts\dist\index.js:34:23)
	at c:\Users\work\.vscode\extensions\mohsen1.react-javascript-to-typescript-transform-vscode-1.10.0\out\src\extension.js:24:41
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\work\.vscode\extensions\mohsen1.react-javascript-to-typescript-transform-vscode-1.10.0\out\src\extension.js:4:58)
```

My VScode details:

```
Version: 1.35.1 (system setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by caleb15** [comment]
Actually same problem as #31
